language: go

go:
  - 1.8.x

install:
 - go get -u -v github.com/kardianos/govendor
 - mkdir -p $HOME/gopath/src/livingit.de/code/
 - cd $HOME/gopath/src/livingit.de/code && ln -s $HOME/gopath/src/github.com/sascha-andres/toggl toggl
 - cd $HOME/gopoath/src/livingit.de/code/toggl && govendor sync && go install
